/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.FilmeDao;
import br.ulbra.entity.Filme;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s.lucas
 */   
public class FrFilmes extends javax.swing.JFrame {

    /**
     * Creates new form FrFilmes
     */
    public FrFilmes() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        controlarBtn(1);
        edId.setEnabled(false);
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnFilmes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        edSin = new javax.swing.JTextField();
        edTitulo = new javax.swing.JTextField();
        edDiretor = new javax.swing.JTextField();
        edId = new javax.swing.JTextField();
        edDurao = new javax.swing.JTextField();
        edTematica = new javax.swing.JTextField();
        edGenero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btSalvar2 = new javax.swing.JButton();
        btAlterar2 = new javax.swing.JButton();
        btExcluir2 = new javax.swing.JButton();
        edLancamento = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFilmes = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btnFiltroF = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adicione seu filme favorito!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 11, -1, 30));

        pnFilmes.setBackground(new java.awt.Color(51, 0, 0));
        pnFilmes.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        pnFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnFilmesMouseClicked(evt);
            }
        });
        pnFilmes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Diretor:");
        pnFilmes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        pnFilmes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Título:");
        pnFilmes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gênero:");
        pnFilmes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lançamento:");
        pnFilmes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Temática:");
        pnFilmes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sinopse:");
        pnFilmes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Duração:");
        pnFilmes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        pnFilmes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        edSin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnFilmes.add(edSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 160, 60));

        edTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnFilmes.add(edTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, -1));

        edDiretor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnFilmes.add(edDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, -1));

        edId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        edId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edIdActionPerformed(evt);
            }
        });
        pnFilmes.add(edId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, -1));

        edDurao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnFilmes.add(edDurao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, -1));

        edTematica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnFilmes.add(edTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));

        edGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnFilmes.add(edGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Preencha os dados");
        pnFilmes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Opções:");
        pnFilmes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        btSalvar2.setText("SALVAR");
        btSalvar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar2ActionPerformed(evt);
            }
        });
        pnFilmes.add(btSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 80, 30));

        btAlterar2.setText("ALTERAR");
        btAlterar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btAlterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterar2ActionPerformed(evt);
            }
        });
        pnFilmes.add(btAlterar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 80, 30));

        btExcluir2.setText("EXCLUIR");
        btExcluir2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir2ActionPerformed(evt);
            }
        });
        pnFilmes.add(btExcluir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 80, 30));

        edLancamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        try {
            edLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edLancamentoActionPerformed(evt);
            }
        });
        pnFilmes.add(edLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, 20));

        jPanel1.add(pnFilmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 440, 380));

        tbFilmes.setBackground(new java.awt.Color(0, 0, 0));
        tbFilmes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbFilmes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbFilmes.setForeground(new java.awt.Color(255, 255, 255));
        tbFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TÍTULO", "GENÊRO", "LANÇAMENTO", "TEMÁTICA", "SINOPSE", "DURAÇÃO", "DIRETOR"
            }
        ));
        tbFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFilmesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFilmes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 670, 90));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7114157_filmmaking_cinematography_movie_studio_film slate_icon.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        btAdd.setBackground(new java.awt.Color(255, 255, 255));
        btAdd.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btAdd.setText("ADICIONAR");
        btAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jPanel1.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 90, 30));

        txtPesquisar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 170, -1));

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btPesquisar.setText("PESQUISAR");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        btnFiltroF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gênero", "Temática", " " }));
        btnFiltroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroFActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltroF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edIdActionPerformed

    private void tbFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFilmesMouseClicked
        Filme f = new Filme();
        controlarBtn(2);
        if (tbFilmes.getSelectedRow() != -1) {
            edId.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 0).toString());
            edTitulo.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 1).toString());
            edGenero.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 2).toString());
            edLancamento.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 3).toString());
            edTematica.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 4).toString());
            edSin.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 5).toString());
            edDurao.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 6).toString());
            edDiretor.setText(tbFilmes.getValueAt(tbFilmes.getSelectedRow(), 7).toString());
        }
    }//GEN-LAST:event_tbFilmesMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        controlarBtn(4);
    }//GEN-LAST:event_btAddActionPerformed

    private void btExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir2ActionPerformed
        Filme f = new Filme();
        try {
            FilmeDao fd = new FilmeDao();
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse registro?",
                    "Excluir registro", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                f.setId(Integer.parseInt(edId.getText()));
                fd.delete(f);
                readJTable();
                controlarBtn(1);
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada com sucesso!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_btExcluir2ActionPerformed

    private void btSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar2ActionPerformed
        Filme f = new Filme();
        try {
            FilmeDao fd = new FilmeDao();
            f.setTitulo(edTitulo.getText());
            f.setGenero(edGenero.getText());
            f.setLancamento(edLancamento.getText());
            f.setTematica(edTematica.getText());
            f.setSinopse(edSin.getText());
            f.setDuracao(edDurao.getText());
            f.setDiretor(edDiretor.getText());
            fd.create(f);
            readJTable();
            controlarBtn(1);
        } catch (SQLException ex) {
            Logger.getLogger(FrUsuario.class
                    .getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btSalvar2ActionPerformed

    private void btAlterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterar2ActionPerformed
        Filme f = new Filme();
        try {
            FilmeDao fd = new FilmeDao();
            f.setTitulo(edTitulo.getText());
            f.setGenero(edGenero.getText());
            f.setLancamento(edLancamento.getText());
            f.setTematica(edTematica.getText());
            f.setSinopse(edSin.getText());
            f.setDuracao(edDurao.getText());
            f.setDiretor(edDiretor.getText());
            fd.update(f);
            readJTable();
            controlarBtn(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btAlterar2ActionPerformed

    private void pnFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnFilmesMouseClicked

    }//GEN-LAST:event_pnFilmesMouseClicked

    private void edLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edLancamentoActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
    
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
          try {
             
            int tipo = 0;
            switch (btnFiltroF.getSelectedIndex()) {
               
                case 0:
                    tipo = 0;
                    break;
                case 1:
                    tipo = 1;

            
            } if (tipo == 0) {
                FGenero(txtPesquisar.getText(), tipo);
            } else {
                FTematica(txtPesquisar.getText(), tipo);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btnFiltroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroFActionPerformed
        
    }//GEN-LAST:event_btnFiltroFActionPerformed
    public void controlarBtn(int op) {
        switch (op) {
            case 1:
                pnFilmes.setVisible(false);
                btSalvar2.setEnabled(true);
                break;
            case 2:
                pnFilmes.setVisible(true);
                btAlterar2.setEnabled(true);
                btExcluir2.setEnabled(true);
                btSalvar2.setEnabled(false);
                break;
            case 3:
                pnFilmes.setVisible(false);
                btAlterar2.setEnabled(true);
                btExcluir2.setEnabled(true);
                break;
            case 4:
                pnFilmes.setVisible(true);
                btAlterar2.setEnabled(false);
                btExcluir2.setEnabled(false);
                btSalvar2.setEnabled(true);

        }
        this.pack();
    }

    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbFilmes.getModel();
        modelo.setNumRows(0);
        FilmeDao fdao = new FilmeDao();
        for (Filme s : fdao.read()) {
            modelo.addRow(new Object[]{
                s.getId(),
                s.getTitulo(),
                s.getGenero(),
                s.getLancamento(),
                s.getTematica(),
                s.getSinopse(),
                s.getDuracao(),
                s.getDiretor()
            });
        }
    }

    public void readJTableForDesc(String titulo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbFilmes.getModel();
        modelo.setNumRows(0);
        FilmeDao mdao = new FilmeDao();
        for (Filme s : mdao.readForDesc(titulo)) {
            modelo.addRow(new Object[]{
                s.getId(),
                s.getTitulo(),
                s.getGenero(),
                s.getLancamento(),
                s.getTematica(),
                s.getSinopse(),
                s.getDuracao(),
                s.getDiretor()
            });
        }
    }
     public void FTematica(String tematica, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbFilmes.getModel();
        modelo.setNumRows(0);
        FilmeDao mdao = new FilmeDao();
        for (Filme s : mdao.filtroTematica(tematica, tipo)) {
            modelo.addRow(new Object[]{
                s.getId(),
                s.getTitulo(),
                s.getGenero(),
                s.getLancamento(),
                s.getTematica(),
                s.getSinopse(),
                s.getDuracao(),
                s.getDiretor()
            });
        }
    }
      public void FGenero(String genero, int tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbFilmes.getModel();
        modelo.setNumRows(0);
        FilmeDao mdao = new FilmeDao();
        for (Filme s : mdao.filtroGenero(genero, tipo)) {
            modelo.addRow(new Object[]{
                s.getId(),
                s.getTitulo(),
                s.getGenero(),
                s.getLancamento(),
                s.getTematica(),
                s.getSinopse(),
                s.getDuracao(),
                s.getDiretor()
            });
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrFilmes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrFilmes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAlterar2;
    private javax.swing.JButton btExcluir2;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar2;
    private javax.swing.JComboBox<String> btnFiltroF;
    private javax.swing.JTextField edDiretor;
    private javax.swing.JTextField edDurao;
    private javax.swing.JTextField edGenero;
    private javax.swing.JTextField edId;
    private javax.swing.JFormattedTextField edLancamento;
    private javax.swing.JTextField edSin;
    private javax.swing.JTextField edTematica;
    private javax.swing.JTextField edTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnFilmes;
    private javax.swing.JTable tbFilmes;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
